# -*- coding: utf-8 -*-
# config.py

# Define configuration parameters

# Set the number of batch size for processing
batch_size = 50

# Set the number of processes (workers) to use for parallel processing
num_processes = 4

# Define a similarity threshold for language caching
similarity_threshold = 90

# Set the Neo4j database settings
neo4j = {
    "uri": "bolt://localhost:7687",  # URI for Neo4j database
    "username": "neo4j",  # Username for Neo4j authentication
    "password": "administrator",  # Password for Neo4j authentication
    "encrypted": False  # Set to True if the connection should be encrypted
}

# Spacy 3.6.0 models for various languages
SPACY_MODELS = {
    'ca': 'ca_core_news_sm',  # Catalan compatible with 3.6.0
    'da': 'da_core_news_sm',  # Danish compatible with 3.6.0
    'de': 'de_core_news_sm',  # German compatible with 3.6.0
    'el': 'el_core_news_sm',  # Greek compatible with 3.6.0
    'en': 'en_core_web_md',  # English compatible with 3.6.0
    'es': 'es_core_news_sm',  # Spanish compatible with 3.6.0
    'fi': 'fi_core_news_sm',  # Finnish compatible with 3.6.0
    'fr': 'fr_core_news_sm',  # French compatible with 3.6.0
    'hr': 'hr_core_news_sm',  # Croatian compatible with 3.6.0
    'it': 'it_core_news_sm',  # Italian compatible with 3.6.0
    'ja': 'ja_core_news_sm',  # Japanese compatible with 3.6.0
    'ko': 'ko_core_news_sm',  # Korean compatible with 3.6.0
    'lt': 'lt_core_news_sm',  # Lithuanian compatible with 3.6.0
    'mk': 'mk_core_news_sm',  # Macedonian compatible with 3.6.0
    'nb': 'nb_core_news_sm',  # Norwegian Bokmål compatible with 3.6.0
    'nl': 'nl_core_news_sm',  # Dutch compatible with 3.6.0
    'pl': 'pl_core_news_sm',  # Polish compatible with 3.6.0
    'pt': 'pt_core_news_sm',  # Portuguese compatible with 3.6.0
    'ro': 'ro_core_news_sm',  # Romanian compatible with 3.6.0
    'sl': 'sl_core_news_sm',  # Slovenian compatible with 3.6.0
    'sv': 'sv_core_news_sm',  # Swedish compatible with 3.6.0
    'ru': 'ru_core_news_sm',  # Russian compatible with 3.6.0
    'uk': 'uk_core_news_sm',  # Ukrainian compatible with 3.6.0
    'xx_ent_wiki': 'xx_ent_wiki_sm',  # Multi-language Entity Recognition  compatible with 3.6.0
    'xx_sent_ud': 'xx_sent_ud_sm',  # Multi-language Sentence Segmentation compatible with 3.6.0
    'zh': 'zh_core_web_sm',  # Chinese compatible with 3.6.0
}

# Language detection model URL
'''
ERCDiDip/langdetect: https://huggingface.co/ERCDiDip/langdetect

Detects languages in the input text and translates it to the target language using a machine translation model.
If the detected language is the same as the target language, no translation is performed.
If a custom translation model is not provided, a default translation model is used based on the detected language.

Detectable Languages:
Modern: Bulgarian (bg), Croatian (hr), Czech (cs), Danish (da), Dutch (nl), English (en),
Estonian (et), Finnish (fi), French (fr), German (de), Greek (el), Hungarian (hu), Irish (ga),
Italian (it), Latvian (lv), Lithuanian (lt), Maltese (mt), Polish (pl), Portuguese (pt),
Romanian (ro), Slovak (sk), Slovenian (sl), Spanish (es), Swedish (sv), Russian (ru),
Turkish (tr), Basque (eu), Catalan (ca), Albanian (sq), Serbian (se), Ukrainian (uk),
Norwegian (no), Arabic (ar), Chinese (zh), Hebrew (he)

Medieval: Middle High German (mhd), Latin (la), Middle Low German (gml), Old French (fro),
Old Church Slavonic (chu), Early New High German (fnhd), Ancient and Medieval Greek (grc)

'''
LANGUAGE_DETECTION_MODEL_URL = 'ERCDiDip/langdetect'

DATASET_FOLDER = 'datasets/'
RAW_DATASET = 'datasets/db.json'
BATCH_FOLDER = 'datasets/batches/'
PATTERN = r'batch_(\d+)\.json'

SPACY_MAPPINGS = {'ORG': ['ORGANIZATION', 'WRK', 'ORG', 'OG', 'MSR', 'orgName'],
 'PERSON': ['DERIV_PER', 'PERSON', 'PRS', 'persName', 'PET_NAME', 'PS'],
 'EVENT': ['EVENT', 'EVT', 'EVN'],
 'GPE': ['GPE', 'LC', 'GPE_ORG', 'geogName', 'GPE_LOC', 'LOC', 'placeName'],
 'PRODUCT': ['PRODUCT', 'PROD', 'OBJ'],
 'DATE': ['PERIOD', 'DATE', 'TME', 'TIME', 'time', 'DATETIME', 'TI', 'DT'],
 'FAC': ['FAC', 'FACILITY'],
 'LANGUAGE': ['LANGUAGE'],
 'LAW': ['LAW'],
 'MONEY': ['MONEY'],
 'NORP': ['NORP', 'date', 'NAT_REL_POL'],
 'WORK_OF_ART': ['WORK_OF_ART'],
 'MOVEMENT': ['MOVEMENT'],
 'OTHER': ['TITLE_AFFIX', 'PHONE', 'MISC', 'DRV'],
 'NUMBER': ['CARDINAL',
  'NUMERIC_VALUE',
  'ORDINAL',
  'QT',
  'QUANTITY',
  'PERCENT']}

ENTITIES_MAPPING = {'ORG': ["Christie's Los Angeles",'Private collection',
   "洛杉磯佳士得",
  "Sotheby's Hong Kong",
  "Sotheby's",
  "Sotheby's New York",
  "Christie's",
  'Private Collection',
  'American Private Collection',
  'Leonard Hutton Galleries',
  'Collection Mrs',
  'European Private Collection',
  "Sotheby's London",
  "Christie's East New York",
  'Kerr Collection',
  "D'Arcy Galleries",
  'the Museum of Fine Arts',
  'Petit Musée',
  'S. Marchant & Son',
  "Christie's London",
  'Arte Primitivo',
  'Royal-Athena Galleries',
  'Galerie Démons',
  'Charles Ede Ltd',
  'Lowther Castle',
  'London Market',
  'Florida Private Collection',
  'the Tuyet Nguyet',
  'Earl of Sandwich',
  "Christie'",
  'Barakat Antiquities',
  'Corte Madera',
  'Butterfield & Butterfield',
  'GENTLEMAN',
  'Christie’s',
  'KILLADOON HOUSE',
  'CRG Gallery',
  'Clarks Auction',
  "Christie's Hong Kong",
  'the Brooklyn Museum',
  'Hotspur Ltd',
  'Mallett & Son Ltd.',
  'Dominique Thirion Gallery',
  'Collection Particulière',
  'New York Private Collection',
  'New York Art Market',
  'Viktor & Edit Baerlocher',
  'Yamanaka & Company',
  'Hurst Gallery',
  'Sotheby’s',
  'the Elizabeth A. Keck Collection',
  'Luxe',
  'Antiquarium',
  'Fortuna Fine Arts',
  'New York Private Collector',
  'Archaeological Center',
  'Sotheby Parke Bernet Inc',
  'the Aoyama Studio Collection',
  'the De An Tang Collection',
  'Japanese Private Collection',
  'Mandi royal collection',
  'Austrian Private Collection',
  'the Hagop Kevorkian Fund',
  'Fine Oriental Manuscripts',
  'Gentry Dog',
  'JAMIESON',
  'Schoonover Studios Ltd',
  'Rossi & Rossi Ltd, London',
  'C.T. Loo',
  'Private Library',
  'Sotheby’s Parke Bernet',
  'Bern',
  'Surena collection',
  'Delbeke House',
  'Foreign Affairs',
  'Consul-General',
  'Empress Alexandra Feodorovna',
  'Fabergé',
  'the Merlin Trust',
  'Gallery Rosen Ancient Art',
  'an Important American Private Collection',
  'Khawam Brothers',
  'Bonhams Hong Kong',
  'Distinguished Midwest Private Collection',
  "Christie's New York",
  'Russian Works of Art',
  'The Groppi Collection',
  'Sotheby & Co',
  "Sold Sotheby's",
  'a Sister of Charity',
  'Cook Collection',
  'Geneva Private Collection',
  'Lonsdale',
  'Lowther Castle',
  'Thorntons of York',
  'Arete',
  'California Private Collection',
  'Antiqua',
  'Ancient Greek Vases Formerly',
  'Deburaux & Associés',
  'Art Market',
  'the Ronald W. Longsdorf Collection |',
  'English Private Collection',
  'Fuse Lighting',
  '中國',
  "Christie's",
  'Provincetown',
  'Hamiltons Gallery',
  'Rugby School Art Museum',
  'Lawrence Collection',
  'Phoenix Ancient Art',
  'Ancient',
  'Taisei Gallery',
  'Bonhams',
  'Manhattan Private Collection',
  'Collection W.J.R. Dreesmann',
  'Collection Professor Dr Drs Anton C.R. Dreesmann',
  'Collection Professeur',
  'Sons Ltd',
  'Bonhams London',
  'Brandeis University',
  'Waltham\xa0',
  'The Purchase Gallery, Inc',
  'Purchase',
  'Jade House',
  '中易公司',
  'Summa Galleries',
  'Eymery & Cie',
  'K. Rabenou Gallery',
  'Duveen Brothers Inc',
  'Royal Athena Galleries',
  'Collection Vincente Huidobro',
  'Arts Primitifs',
  'Collection',
  'Pine and Stone Retreat Collection',
  'the Dafengtang Collection',
  'Hôtel Drouot',
  'Universität Zürich',
  'Guinevere Antiques Ltd',
  'Fortuna Fine Arts',
  'Ltd',
  'FROM THE COLLECTION OF BENOÎT DE GORSKI',
  'King of Hanover',
  'Leo Castelli Gallery',
  'Hôtel Drouot',
  'Sotheby’s London',
  'Princeton Gallery of',
  'Fine Art',
  'Christie’s Paris',
  'Mitsukoshi Department Store',
  'Summa Galleries, Inc',
  'Ikeda Gallery',
  'Piasa',
  'Hall & Knight',
  'Musée Bourdelle',
  'Musée National de la Céramique à Sèvres',
  'Mason Antiques',
  'Cohen & Cohen',
  "Sold Christie's",
  'Frank Sternberg AG',
  'Karen Brown Gallery',
  'The Thomas Vroom Collection',
  'Zurich',
  'Diplomatic Private Collection',
  'J.T. Tai & Co',
  'Indianapolis Museum of Art',
  'Osterrieth House',
  'Crounce Family',
  'Important American Furniture, Silver, Folk Art and Decorative Arts',
  'The Castle Ashby Vases',
  'Fine Antiquities',
  'Villa Visconti Alari',
  'Private Collection',
  'Mallett & Son Ltd',
  'French private collection',
  'R.H. Ellsworth Ltd',
  'Collection Mrs',
  "Sotheby'",
  'Wellington Hotel',
  'Duran Arte y Subastas',
  'Wou\xa0Lien-Pai Museum',
  'an Important Private Collection',
  'the Science Museum',
  'Ginac Collection',
  'Far-East Gallery',
  'Topper Gallery',
  'Yale Burge Antiques',
  'Bedelle Jewelry Collection',
  'Superior Galleries',
  'European Collection',
  'Robert B',
  'The Dr Anton C.R.',
  'the Erlenmeyer Collection',
  'Art of the Ancient World',
  'Sotheby Parke Bernet',
  'Texas Private Collection',
  'the Los Angeles Opera',
  'Collection',
  'Chinese Porcelain Company',
  'the Delmore Gallery',
  'Safani Gallery',
  'Harewood House',
  'Roger Peyrefitte collection',
  'Antiquities Ltd',
  'Sycomore Ancient Art',
  'Arte alla Riva',
  'the British Coffee House',
  'Hong Kong Private Collection',
  'Graven Images',
  'THE G. SANGIORGI COLLECTION',
  'Eid & Son',
  'The Red Crescent',
  'the Pinto Collection',
  'Ashburnham Place',
  'Antiques',
  "Charge d'Affaires",
  'the Embassy of the Netherlands',
  'Swiss Art Market',
  'Bob P. Haboldt & Co',
  'Superior Galleries',
  'Kodner Galleries',
  'the Worcester Art Museum',
  'Sotheby Parke Bernet, Inc.',
  'Swiss Private Collection',
  'INC',
  'Anastos Collection',
  'Ascot',
  'The Sven Gahlin Collection',
  "Christie's South Kensington",
  'J.D. van Oenen',
  'Rollin & Feuardent',
  'Hartman Rare Art',
  'Benjamin Wolff Collection',
  "The Wolff Collection' Sale",
  'Leo Gallery',
  'Appuldurcumbe House',
  'Bohler',
  'Sotheby Parke Bernet, Inc. New York',
  'The Leicester Galleries',
  'ex-H. Mol Collection',
  'Galerie Numaga',
  'F. Low-Beer & Co',
  'Arts Nouv',
  'Hôtel Drouot',
  'The Dillée Collection',
  'The Leo Mildenberg Collection of Ancient Animals',
  'Keir',
  'Carlton House Terrace',
  'Heytesbury House',
  'The Berkshire Museum',
  'Northeast Auctions',
  'Galerie 41',
  'Galerie',
  'H. Mansour Collection',
  'Fine and Decorative Art',
  'G. McKinley Collection',
  'Bonham',
  'Pennsylvania Private Collection',
  'The Meulendijk Collection of Tribal Art',
  'Antiquair K. Grusenmeyer',
  'Henningsen Collection'],
 'OTHER': ['Myth',
           'Myth and Reality',
  'PRINCELY',
  'B004',
  'n°',
  'Cinq-Mars',
  'Merveilles',
  'HON',
  'KP',
  'kilga',
  'Sureda',
  'Surena',
  'C007',
  'C164',
  'Sa vente',
  '1083',
  '288',
  'D001',
  'D001',
  'Auktion XVIII',
  'Pomarancio -/ a.d',
  'Gold & Silver Auction Part II',
  'Renaissance',
  'D73',
  'D040',
  'Chili',
  'J034',
  'Purportedly',
  'E017',
  'E19',
  'PROPERTY',
  'SELECTED PAINTINGS',
  '3632',
  'Ägyptische',
  'Ägyptologische Hefte',
  'Orientalischen Seminars',
  'Item two',
  'Royal',
  'B85',
  'B009',
  'Afd.26/3',
  'ca',
  'M.4.10',
  'Ecoute',
  '6040',
  'Sold Without Reserve',
  'Q.9.37',
  'D52',
  'D032',
  'D52',
  'l’',
  'Ancient Vases',
  'B111',
  'B010',
  'Vente',
  'B111',
  'Esq,',
  'Metal Vases',
  'Coeur',
  'Sr',
  'J57',
  'J017',
  'CHI',
  'collected',
  'Transmis',
  'MASTERPIECES',
  'Fragments of Time',
  'F021',
  'Estates',
  'Abby',
  'D068',
  'B033',
  'Vente',
  'B033',
  'Item ten',
  'Arrow',
  'Arts d’orient-',
  'K.B.E. SOLD BY ORDER OF',
  'EXECUTORS',
  'Hart',
  'BUTLER',
  'Commissaire-priseur',
  'Artist',
  'lot5',
  'ROCAILLE',
  'Faces From The Ancient World',
  'CORD',
  'Tim D. Wright Master Drawings',
  'nbr'],
 'NORP': ['Chinese',
  'German',
  'Belgian',
  'French',
  'English',
  'Dutch',
  'CHINE',
  'Japanese',
  'European',
  'Spanish',
  'Swiss',
  'American',
  'Taiwanese',
  'Asian',
  'Coptic',
  'Moorish',
  'African',
  'Oceanic',
  'Ex-German',
  'Egyptian'],
 'PERSON': ['Julius Eberhardt','Miss Marianne C.J. Eras',
  '朱利思∙',
  '艾伯哈特',
  'Karim Grusenmeyer',
  'Abraham Rosman',
  'Paula Rubel',
  'Frederick Henry von Schleinitz',
  'Marcel Bissey',
  'Emmanuel Moatti',
  'Robert Bloch',
  'Alexandre Iolas',
  'Filipino',
  'Charles Ede',
  'Quincy Chuang',
  'Maurice Bonnefoy',
  'James Barzyk',
  'Alex Philips',
  'Susan Kloman',
  'Spier',
  'Wou Kiuan',
  'Wou Lien-Pai Museum',
  'Sui Yuan',
  'John J. Klejman',
  'Martin',
  'Giovanni Vincitore Ruggiero',
  'Mabel Markey',
  'John Joseph Ruggiero',
  'Agnes Dympna',
  'McKenna',
  'Ernst Langlotz',
  'Cahn',
  'Kofler',
  'JM Béalu et fils',
  'Joseph Hume',
  'John Bedford',
  'William Philip Molyneux',
  '4th Earl',
  'Sefton',
  'Stephen Markbreiter Collection',
  'Mathias Komor',
  'Mathilda Goldman',
  'David Garth',
  'Susan Warner',
  'Henry Pelham',
  'Archibald Douglas Pelham-Clinton',
  'Henry Francis Hope Pelham-Clinton-Hope',
  'Heape',
  'Nathaniel Clements',
  '2nd Earl',
  'Edric van Vredenburgh Collection',
  'Samuel P. Avery',
  'George Terasaki',
  'Alfred E. Mirsky',
  'Kurt Deppert',
  'Elie Borowski',
  'Browne K.P.',
  'ROSALINDE',
  'William Cary',
  'Lois Crane',
  'Hei Hung-Lu',
  'Giorgio Sangiorgi',
  'Cornelius Vermeule',
  'Denny Pinkus',
  'Robert Deutch',
  'Ralph M',
  'Kurokawa',
  'Thomas Barlow Walker',
  '德安堂藏玉',
  'Ramos Studio',
  'Theodore Graf',
  'Kai-Yin Lo 羅啟姸收藏',
  'Magdeleine Blanche',
  'Nolie Croset',
  'Richard Burnett',
  'J. Sam Houston',
  'Adonna Houston',
  'Larry Mooney',
  'Popo DeBathe',
  'Lynne Bell',
  'Billy Jamieson',
  'Rossi',
  'Frank Caro',
  '盧芹齋',
  'Sleiman Aboutaam',
  'Charles Pankow',
  'K. A. Moosberg',
  'Elsa Bloch-Diener',
  'Edward I. Farmer',
  'Christopher Sheppard',
  'José Felipe de Alcover',
  'Sureda',
  'Louis Battenberg',
  'Princess Victoria',
  'Empress',
  'Blanche Ryan',
  'Merlin Montagu Douglas Scott',
  'Kunsthandel Nicolaas Beets',
  'Anton C.R. Dreesmann',
  'Laren',
  'Anton C.R. Dreesmann Collection',
  'Marianne Dreesmann',
  'Jean-Pierre Laprugne',
  'Tom White',
  'Susan\xa0Ollemans',
  'Gisèle Croës',
  'Dan E. Richardson',
  'Richardson',
  'Junkunc',
  'Stephen Junkunc',
  'Joseph Leeson',
  'Elizabeth',
  'Félix Houphouët-Boigny',
  'Oscar Blum Gentilomo',
  'Sam Fogg',
  '巴塞隆',
  'Nicholas T. Molnar',
  '史蒂芬',
  'Simon Spero',
  'Agnes Mary Berkeley',
  'Robert Valentine\xa0',
  'Francis Cook',
  'Renaud Gillet',
  'William',
  'Second Earl',
  'R. Schmidt',
  'Merton D. Simpson',
  'Christopher B. Hemmeter',
  'Kevin Conru',
  'Anton Pestalozzi',
  'Jean-Marc Roudinesco',
  'Jean-Marc\xa0Roudinesco',
  'Jean Wanecq',
  'Werner Schatz',
  'Schatz',
  'Ronald W. Longsdorf',
  'Herbert Kühn',
  'Mary Western Hugessen',
  'Edward Knatchbull',
  'Howard Lipman',
  'JO KOBACKER',
  'John',
  'Somers',
  'Lawrence',
  'M.H. Bloxam',
  'Matt',
  'Nic',
  'N. Koutoulakis',
  'Hilary Chelminski',
  'Edric van Vredenburgh',
  'S.J. Phillips',
  'Frank Partridge',
  'Sammlung  Hans Koenig',
  'Paul Kantor Gallery',
  'Bernice Clyman',
  'M. Gillingham',
  'C.K. Liang',
  '梁宗亢',
  'ERIKA POHL-STRÖHER',
  'Erika Pohl-Ströher',
  'Eymery',
  'Wilfrid Sloane',
  'John Pierpont Morgan',
  'John D. Rockefeller',
  'Jr',
  'J. Uzan',
  'Anthony Meyer',
  'Nicolas Koutoulakis',
  'René Withofs',
  'Dr Drs Anton C.R. Dreesmann',
  'Pierre Bordes',
  'Marcel',
  'Dragesco-Cramoisan',
  'Robert Berkeley',
  '石山房',
  'Luigi Laura',
  'Jacob Epstein',
  'Loudmer',
  'Rudolf Schmidt',
  'Samuel Rogers',
  'Carl J. Ulman',
  'Alfred Chester Beatty',
  "Comtesse d'Aubigny",
  'Carl Kempe',
  'Ernest Cassel',
  'Daphne Zimmermann',
  'Frederick',
  'King George II',
  'King William IV',
  'Prince Ernst Augustus',
  '1st Duke',
  'King George III',
  'George V',
  'Ernst Augustus II',
  'Crown Prince',
  'Ernst Augustus III',
  'Ernst Augustus IV',
  'Donati',
  'Anita Gray Gallery',
  'Edric van Vredenburgh',
  'Edward T.\xa0Chow',
  'Emmanuel de Monbrison',
  'Colin Gross',
  'Herbert Stern',
  'Michelham',
  'M. Parish-Watson',
  'F. Warrington-Strong',
  'Di Castro',
  'Luisa Vertova',
  'Stieglitz',
  'Alma Morganthau',
  'Hayashi Gonsuke',
  'Robert\xa0Berkeley',
  'Robert Martin Berkeley',
  'Naim Attallah CBE',
  'William E.',
  'Anne H. Lewis',
  'Van Berchem',
  'Holger Rosell',
  'Holger',
  '斯德哥爾摩',
  'Henry Clarke',
  'Bruce Anderson',
  'JAMES E. SOWELL',
  'Walter N. Rothschild',
  'Walter',
  'Rothschild',
  'Carlo Cristi',
  'Darwin',
  'Garth',
  'M. van den Ende',
  'Arthur\xa0M.\xa0Sackler',
  'W. Forbes',
  'Jane Ramsey',
  'A.G. Langlois',
  'Langlois',
  'Marguerite Riordan',
  'Gustave Jéquier',
  'Spencer Joshua Alwyne Compton',
  'James Willis',
  'Michael Smurfit',
  '安思遠',
  'William Suddaby',
  'John Granville Morrison',
  'Zuluaga',
  'Necker',
  'Berkowitsch',
  'Wou\xa0Kiuan',
  'Herbert Irving',
  'Princess Patricia of Connaught',
  'Patricia',
  'Mountbatten',
  '牡丹堂',
  'Nicolier',
  'C. J. Devine',
  'Alton Edward Mills',
  'Roger Keverne',
  'Marianne L. Dreesmann-van der Spek',
  'Robert B. Woodward',
  'Woodward',
  'Dikran G. Kelekian',
  'Abby Aldrich Rockefeller',
  'Winthrop Rockefeller',
  'David Rockefeller',
  'Hans',
  'Marie-Louise Erlenmeyer',
  'Yanick van Ruysevelt',
  'Henry de Montherlant',
  'Roger Peyrefitte',
  'Oliver Sears',
  'Keith Howard',
  'Joan Howard',
  'Maria Pergay',
  'Alain Chenel',
  'P. Czinner',
  'John Sparks',
  'MARKO',
  'Harewood',
  'R.A. Jude',
  'Jude',
  'Tristan Tzara',
  'CHARLES W. NEWHALL',
  'Jean Olansizyn',
  'Thomas Cordis m. Hannah Cordis',
  'Thomas Cordis',
  'Cord Cordis',
  'Francis Temple Cordis m. Ruth Ann Prescott',
  'Thomas Francis Cordis m. Annie Byrd Colton',
  'Thomas Edward Cordis m. Annie Marguerite Holden',
  'Edward Colton Cordis m. Mary Elizabeth Walcott Grabe',
  'Mary Anne Cordis',
  'Stanley Gordon Moriarty',
  'Todd Barlin',
  'Charlier',
  'Carlo Perone-Capano',
  'Ulick de Burgh',
  'Clanricarde',
  'Hariett Marchioness',
  'Hubert George de Burgh-Canning',
  'Henry Lascelles',
  'Edward Smith',
  'Andrew Hartnagle',
  'Athos Moretti',
  'Gordian Weber',
  'Ip Yee',
  'Jenny Lewis',
  'Jenny',
  'Ari Vos',
  'D. T. Bowring',
  'Oliver Hoare',
  'Christopher Gibbs',
  'Morris J. Pinto',
  'Murray Frum',
  'Roberta Entwistle',
  'William Boyce Thompson',
  'William Boyce',
  'Thompson',
  'George Halpern',
  'Ashburnham',
  'Catherine Ashburnham',
  "George O'Neill",
  "Needham's",
  'Axel Vervoordt Antwerpen',
  'Leo Biaggi de Blasys',
  'J. H. Zeeman',
  'Paul Kasmin Gallery',
  'Prince Eugene',
  'Savoy Carignano',
  'Henry H. Gorringe',
  'HENRY H. GORRINGE',
  'Norman Norell',
  'George Zacos',
  'A.J. Burniston',
  'Arthur M. Sackler',
  '佳士得',
  'Edwina',
  'Anatole Demidoff',
  'Palazzo San Donato',
  'Charles Pillet',
  'San Donato',
  'Rothschild',
  'Michał Tyszkiewicz',
  'P. Hamonic',
  'Pierre and',
  'Bruun Rasmussen',
  'Edgar Vincent',
  "Lady d'Abernon",
  'Richard Worsley',
  'Margaret Nash',
  'Philippe Laeremans',
  '現藏家',
  'Gordon Partridge',
  'Patti Cadby Birch',
  'Everett B. Birch',
  'Charles-Edouard Duflon',
  '肯普',
  'Nina Borowski',
  'Amlash Pottery',
  'J. Settgast',
  'Archibald Stirling',
  'William Joseph Stirling',
  'Richard D.',
  'Billie Lou Wood',
  'Alfred Morrison',
  'Hester Sassoon',
  'née Gatty',
  'Siegried Sassoon',
  'George Sassoon',
  'Feldman',
  'Albert Spaulding',
  'Richard H. Cord',
  'K. Woodard',
  'Susan',
  'Raymond Egan',
  'David Jones',
  'Dikran Kelekian',
  'Ellen Moeller',
  'Alexander Schreiber',
  'Possibly Loed van Bussel',
  'Cornelis Pieter Meulendijk',
  'Ben Heller',
  'Zakaria Collection',
  'Hadji Baba',
  'Anthony Jacobs',
  'Wilhelm Horn'],
 'GPE': ['Nagel Stuttgart',
  'Paris',
  'New York',
  'Wisconsin',
  'Cairo',
  'U.S.',
  'Laren',
  'London',
  'UK',
  'Munich',
  'Chicago',
  'Melbourne',
  'Boston',
  'USA',
  'Montreal',
  'Canada',
  'U.S',
  'Hong Kong',
  'Brooklyn',
  'Queens',
  'Queens',
  'MIAMI',
  'Bonn',
  'Basel',
  'Lonsdale',
  'Westmoreland',
  'U.K.',
  'Jerusalem',
  'California',
  'San Francisco',
  'Israel',
  'LUGGALA',
  'Switzerland',
  'Newcastle',
  'Clumber Park',
  'Nottinghamshire',
  'Lincoln',
  '巴黎',
  'Leitrim',
  'Liskaerd Cornwall',
  'Liskaerd, Cornouailles',
  '香港',
  '布魯克林',
  '布魯克林',
  'Europe',
  'Brussels',
  'Frankfurt',
  'Germany',
  'Oranmore',
  'Exton Park',
  'Rutland',
  'Syon Lodge',
  'Vienna',
  'Gallen',
  'Osaka',
  '大阪',
  'Rome',
  'Cambridge',
  'MA',
  'Jaffa',
  'Tel Aviv',
  'Japan',
  'Minneapolis',
  'U.S.A.',
  '日本',
  'Lebanon',
  'Beirut',
  'Geneva',
  'Oakland',
  'Austria',
  'France',
  'Long Beach',
  'Virginia',
  'Iowa',
  'Toronto',
  'London',
  'Egypt',
  'New Jersey',
  'Antwerp',
  'the Middle East',
  'Rabat',
  'St Petersburg',
  'Amsterdam',
  'London',
  'Milltown',
  'Russborough House',
  'County Wicklow',
  'Leitrim',
  'the Republic of the Ivory Coast',
  'Segarra',
  'Barcelona',
  'Imre',
  '台灣',
  'Shanghai',
  'China',
  'Wyndham',
  'Buffalo',
  'Seattle',
  'Lausanne',
  'Bessborough',
  'Cumberland',
  'Honolulu',
  'Zurich',
  'Jacaranda',
  'Neuilly',
  'Basel',
  'Los Angeles',
  'Freiburg',
  'Cologne',
  'Wuppertal',
  'Mainz',
  'Wittelsbach',
  'Bayville',
  'Maui',
  'Stuttgart',
  'Beverly Hills',
  'Sidney',
  'Scarsdale',
  'Bath',
  'Somerset',
  'Freiburg',
  'St Honoré',
  'Mazandaran',
  'Iran',
  'Geneva',
  'Loudmer',
  'Giza',
  'Algeria',
  'Belgium',
  'Italy',
  '黎氏',
  'Londres',
  'Solothurn',
  'Hamburg',
  'Wales',
  'Great Britain',
  'Hanover',
  'Teviotdale',
  'Brunswick',
  'Portugal',
  'Lugano',
  'Portobello Road',
  'Londres',
  'Portobello Road',
  'Lyon',
  'Wertheim',
  'An American Place',
  'New Haven',
  'Connecticut',
  'Princeton',
  'Columbus',
  'Ohio',
  'Nihonbashi',
  'Tokyo',
  '東京',
  'Stockholm',
  'Monaco',
  'Cornwall',
  'Rome',
  'Monaco',
  'Milan',
  'Bruxelles',
  'Londres',
  'Netherlands',
  '洛杉磯',
  'Delaware',
  'Maine',
  'The Hague',
  'La Haye',
  'Tehran',
  'Cazenovia',
  'Jersey',
  'Suisse',
  'Indianapolis',
  'Altamont',
  'Stonington',
  'Northampton',
  'Castle Ashby',
  'Drouot',
  'Cernusco sul Naviglio',
  'Milan',
  'Woodland Hills',
  'Florida',
  'Madrid',
  'Spain',
  'ALHAMBRA',
  'Australia',
  'Reno',
  'Nevada',
  'Nîmes',
  'Northumberland',
  'Quai Voltaire',
  'Antwerpen',
  'Petit Jean Mountain',
  'Arkansas',
  'Berne',
  'Texas',
  'Dublin',
  'Thailand',
  '泰國',
  'Dubai',
  'Delmore Downs Station',
  'Northern Territory',
  'Sydney',
  'Yorkshire',
  'France',
  'Ascona',
  'Massachusetts',
  'Longmeadow',
  'Litchfield',
  'Suffield',
  'Cortina',
  'Damascus',
  'Suez',
  'Breda',
  'England',
  'New York City',
  's-Gravenwezel',
  'Beijing',
  '北京',
  'Los Angeles',
  'Habsburg',
  'Kansas City',
  'Dania Beach',
  'Litzelstetten',
  'Sipplingen',
  'the Greek Islands',
  'Leeds',
  'Florence',
  'Ferrières',
  'Seine-et-Marne',
  'Rome',
  'Copenhagen',
  '上海',
  'Isle of Wight',
  'Yarborough',
  'Brocklesby Park',
  'Münich',
  '瑞士',
  'United Kingdom',
  'U.A.E.',
  'Asia',
  'Auxerre',
  'Mediterranean World',
  'Wiltshire',
  'Edinburgh',
  'Pittsfield',
  'Pittsfield',
  'Bar Harbor',
  'Seal Harbor',
  'Manchester',
  'New Hampshire',
  'SYDNEY',
  'Lempertz',
  'Rotterdam', 'E.T. Hall'],
 'DATE': ['December 1982',
  'December 1992',
  'December 2001',
  'December 2002',
  'Zurich 12 May',
  'April 2010',
  'March',
  'December 1995',
  '24th November',
  '14 June 2000',
  'December 1977',
  '4 June 1999',
  'March 2008',
  'July 1992',
  'March',
  'October 2017',
  'October 2018',
  'December 1999',
  'December 2003',
  'December 2000',
  '1985',
  'May 2013',
  'June 1989',
  'June 2006',
  'June 2003',
  'June 15th',
  'April',
  'December',
  'Century',
  '21st May 2009',
  '1892',
  '4 June 2015',
  'February 2017',
  'October 1985',
  'June 2014'],
 'NUMBER': ['XII', '3653', 'two', 'XXV'],
 'MONEY': ['52,000', '269 livres', '212（美金8,']}



